project_name: k6registry
version: 2

before:
  hooks:
    - go mod tidy

dist: build/dist
builds:
  - goos: ["linux", "windows", "darwin"]
    goarch: ["amd64", "arm64"]
    flags: ["-trimpath"]
    env: ["CGO_ENABLED=0"]
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.appname={{.ProjectName}}"
    dir: cmd/k6registry
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

archives:
  - id: bundle
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next+{{.ShortCommit}}{{if .IsGitDirty}}.dirty{{else}}{{end}}"
