FROM golang:1.22.9-alpine3.20

RUN addgroup -g 127 -S docker && adduser -D -u 1001 -G docker runner && \
    apk update && apk add git

COPY k6registry /usr/bin/

USER runner

ENTRYPOINT ["k6registry"]
