FROM debian:12.6-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && update-ca-certificates && \
    addgroup --system --gid 127 docker && adduser --uid 1001 --gid 127 --disabled-password runner

COPY k6registry /usr/bin/

USER runner

ENTRYPOINT ["k6registry"]
