cat > metrics_gen.go <<EOF
// Code generated by metrics_gen.sh, DO NOT EDIT.

package k6registry

var metricsHelps = map[string]string $(jq -c '.["$defs"].metrics.properties | to_entries | map({key:.key, value: .value.description}) | from_entries' docs/registry.schema.json)

EOF