name: Release

on:
  push:
    tags: ["v*.*.*"]

permissions: {}

jobs:
  release:
    name: Release
    uses: grafana/xk6/.github/workflows/tooling-release.yml@0b7fdcb9263312b71deb117994309858119f020d # v1.3.7
    permissions:
      contents: write
      packages: write
      id-token: write
    with:
      go-version: "1.25.x"
      goreleaser-version: "2.8.2"
      k6-versions: '["v1.2.3","v1.0.0"]'